### ISSUE TITLE
podSecurityContext

### ISSUE THREAD

**Issue by jr0dd** [k8s-at-home/container-images#105]
# Details

**Image name:**

transmission

**What steps did you take and what happened:**

added the following to the values.yaml

```
podSecurityContext:
   runAsGroup: 777
   runAsUser: 777
   supplementalGroups:
   - 1000
```

**What did you expect to happen:**

runAsUser and RunAsGroup to update the user and group id's of the kah user.

**Anything else you would like to add:**
output when i exec into the pod

```
kubectl exec -it transmission-7f8bd9dfc6-xkdjx -- bash
groups: cannot find name for group ID 777
groups: cannot find name for group ID 1000

Welcome to a k8s@home container,
```

** additional info
/etc/group
`kah:x:568:`

/etc/passwd
`kah:x:568:568::/home/kah:/usr/sbin/nologin`
