### ISSUE TITLE
[plex] automate applying certificates from cert-manager

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#11]
Problem: 

If you choose to not use Plex remote access and want expose Plex to your a subdomain, streams will be unencrypted. Plex allows you to set a custom cert but it only accepts `pkcs12` format.

With [cert-manager](https://cert-manager.io/) the secret for letsencypt resembles:

```yaml
apiVersion: v1
kind: Secret
data:
  tls.crt: "<base64 crt>"
  tls.key: "<base64 key>"
```

The process for converting this is `openssl pkcs12 -export -passout pass:${PASSWORD} -inkey ${NAME}.key -in ${NAME}.crt -out ${NAME}.pfx`

These can be defined in Plex `Preferences.xml` with the `customCertificateDomain `, `customCertificatePath` and `customCertificateKey` keys

Lastly the cert will need to be updated when it is renewed.

Not sure yet if this is best handled by:

- a initContainer in the plex chart to generate the `pkcs12` cert
- a cronjob to copy the cert secret from a namespace and create a secret with the `pkcs12` cert in the namespace plex lives in

Cronjob seems the most effective since this will run and renew the cert if needed.

**Comment by Ornias1993** [comment]
With Cert Manager 1.2.0 i think they have a way of handling pkcs12  now ;-)

**Comment by onedr0p** [comment]
> With Cert Manager 1.2.0 i think they have a way of handling pkcs12  now ;-) 

I saw that in the release notes, super excited. Hopefully I can grab sometime to hack at it

**Comment by onedr0p** [comment]
This is possible without the need for any helper scripts in the images.

Tools needed installed in cluster:
- cert-manager
- emberstack/reflector
- stakater/reloader

## 1. Create a secret with the value being a generated encryption key to the resulting `pkcs12` cert

For this example the password will be `by87f73q8f438qg7g3qgrds`

## 2. Add a `pkcs12` keystore to your cert-manager `Certificate` and also add the annotations to where to reflect the cert to.

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tld
  namespace: kube-system
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: "media"
spec:
  secretName: domain-tld-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "domain.tld"
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: domain-tld-pkcs12
        key: key
  dnsNames:
  - "domain.tld"
  - "*.domain.tld"
```

## 3. Using the `plex-media-server` chart mount in the secret

```
additionalVolumeMounts:
- name: cert
  mountPath: "/config/certs"
  readOnly: true
additionalVolumes:
- name: cert
  secret:
    secretName: domain-tld-tls
    items:
    - key: keystore.p12
      path: domain-tld-tls.p12
```

## 4. Add the `podAnnotation` to restart the pod when the secret changes

```yaml
podAnnotations:
  secret.reloader.stakater.com/reload: "domain-tld-tls"
```

## 5. Using `env` or manually set cert location, cert password and cert-domain in Plex Network Settings

```yaml
env:
  PLEX_PREFERENCE_1: "customCertificatePath=/config/certs/domain-tld-tls.p12"
  PLEX_PREFERENCE_2: "customCertificateKey=by87f73q8f438qg7g3qgrds"
  PLEX_PREFERENCE_3:  "customCertificateDomain=domain.tld"
```
