### ISSUE TITLE
Failed to mount ReadWriteMany volumes because of missing nfs tools

### ISSUE THREAD

**Issue by mikevader** [k8s-at-home/container-images#201]
# Details

**Image name:**

Plex

**What steps did you take and what happened:**

On my plex I have several volumes of type PVC with access mode `ReadWriteOnce`. Those work fine.

I tired add an additional volume (`audiobook2`) with access mode `ReadWriteMany` (from Longhorn) with the following configuration:

```
plex:
  image:
    repository: ghcr.io/k8s-at-home/plex
    tag: v1.25.9.5721-965587f64
  env:
    PLEX_UID: 568
    PLEX_GID: 568
    PLEX_CLAIM: "claim-..."
    PLEX_PREFERENCE_0: "allowedNetworks=..."
  persistence:
    config:
      enabled: true
      nameOverride: "-"
      type: pvc
      size: 5Gi
      accessMode: ReadWriteOnce
      retain: true
    transcode:
      enabled: true
      type: emptyDir
      mountPoint: /transcode
    tv:
      enabled: true
      type: pvc
      size: 500Gi
      readOnly: true
      accessMode: ReadWriteOnce
      mountPath: /mnt/media/tv
    audiobooks:
      enabled: true
      type: pvc
      size: 20Gi
      readOnly: true
      accessMode: ReadWriteOnce
      mountPath: /mnt/media/audiobooks
    audiobooks2:
      enabled: true
      type: pvc
      size: 20Gi
      readOnly: true
      accessMode: ReadWriteMany
      mountPath: /mnt/media/audiobooks2
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
probes:
  ...
ingress:
  ...
```

After adding the new volume I saw in Longhorn, that the volume was created with the correct access mode and attached to the correct node.

The pod although was not able to start up because of the following errors:
```
Unable to attach or mount volumes: unmounted volumes=[audiobooks2], unattached volumes=[movies transcode tv kube-api-access-lqqd7 audiobooks audiobooks2 config]: timed out waiting for the condition
```
```
MountVolume.MountDevice failed for volume "pvc-0a89574d-3157-42fe-83cf-2367a62768fd" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/local/sbin/nsmounter Mounting arguments: mount -t nfs -o vers=4.1,noresvport,soft,intr,timeo=30,retrans=3 10.43.6.189:/pvc-0a89574d-3157-42fe-83cf-2367a62768fd /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0a89574d-3157-42fe-83cf-2367a62768fd/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0a89574d-3157-42fe-83cf-2367a62768fd/globalmount: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

From a short google search I suspect that maybe the `nfs-common` package is missing or is somehow not available in this context.

**What did you expect to happen:**

That NFS mounts work out of the box without special configuration. I assume this because of this example: https://github.com/dirtycajunrice/gitops/blob/master/cluster-apps/plex/values.yaml#L55-L63

**Anything else you would like to add:**

I use the standard longhorn persistence class.

**Additional Information:**

My intention is to use RWX volumes so I can mount it in another pod for easier upload. If there are other good solutions for that, I'm interested as well.
