### ISSUE TITLE
[network-ups-tools] Has anyone gotten a slave setup to work?

### ISSUE THREAD

**Issue by cdeadspine** [k8s-at-home/container-images#34]
I have a master setup working ok
```
image:
  repository: k8sathome/network-ups-tools
  tag: v2.7.4-2124-g9defa7a9 #v2.7.4-2061-g46c7da76
  pullPolicy: IfNotPresent

controllerType: daemonset #https://github.com/k8s-at-home/charts/blob/master/charts/common/values.yaml

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: ups-device
          operator: Exists

securityContext: #requird to access hardware
  privileged: true

service:
  port:
    name: server
    port: 3493

env: {}
  # TZ: UTC

additionalVolumes:
  - name: ups
    hostPath:
      path: /dev/bus/usb
  - name: kp
    hostPath:
      path: /usr/local/killpower #k3os specific path
additionalVolumeMounts:
  - mountPath: /dev/bus/usb
    name: ups
  - mountPath: /killpower
    name: kp
  
# The main configuration files for network-ups-tools
config:
  # If set to 'values', the configuration will be read from these values.
  # Otherwise you have to mount a volume to /etc/nut containing the configuration files.
  mode: values

  # See https://github.com/networkupstools/nut/tree/master/conf for config sample files
  files:
    nut.conf: |
      MODE=netserver

    upsd.conf: |
      LISTEN 0.0.0.0

    ups.conf: |
      [ups1]
        driver = usbhid-ups
        port = auto
        desc = "apc on usb"
    
    upsd.users: |
      [monmaster]
        actions = SET
        instcmds = ALL
        password  = secret
        upsmon master
      [monslave]
        password  = secret
        upsmon slave

    upsmon.conf: | 
      MONITOR ups1@localhost 1 monmaster secret master
      SHUTDOWNCMD "/usr/local/ups/sbin/upsdrvctl shutdown && touch /killpower/killpower" 
```

I can't get a slave setup to work, it seems to be trying to load a "dummy device" and I don't know why, or how to disable such a thing
```
Network UPS Tools - Device simulation and repeater driver 0.14 (2.7.4-2124-g9defa7a9)
Network UPS Tools - UPS driver controller 2.7.4-2124-g9defa7a9
Can't open dummy-ups definition file /etc/nut/dummy-ups.dev: Can't open /etc/nut/dummy-ups.dev: No such file or directory
Driver failed to start (exit status=1)
```

I tried adding a fake dummy, i tried adding a blank ups.conf, i don't see anywhere in the documentation about how to disable the dummy driver, or why a slave would require such a thing at all? I see the "dummy" sometimes referred to as a "repeater" i have no idea what that means or if it is required for slave mode

If the dummy is some kind of default automatically always run thing (on mode=netclient), then maybe just a file is missing in this image /etc/nut/dummy-ups.dev?
```
#non working slave example
image:
  repository: k8sathome/network-ups-tools
  tag: v2.7.4-2124-g9defa7a9 #v2.7.4-2061-g46c7da76
  pullPolicy: IfNotPresent

controllerType: daemonset #https://github.com/k8s-at-home/charts/blob/master/charts/common/values.yaml

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: ups-device
          operator: DoesNotExist

securityContext: #requird to access /usr/local/killpower
  privileged: true

env: {}
  # TZ: UTC

additionalVolumes:
  - name: kp
    hostPath:
      path: /usr/local/killpower #k3os specific path
additionalVolumeMounts:
  - mountPath: /killpower
    name: kp
  
# The main configuration files for network-ups-tools
config:
  # If set to 'values', the configuration will be read from these values.
  # Otherwise you have to mount a volume to /etc/nut containing the configuration files.
  mode: values

  # See https://github.com/networkupstools/nut/tree/master/conf for config sample files
  files:
    nut.conf: |
      MODE=netclient
      ALLOW_NO_DEVICE=true  #maybe this is required? i dont know
      export ALLOW_NO_DEVICE
    
    upsmon.conf: |
      MONITOR ups1@each-master-ups-network-ups-tools.default.svc.cluster.local:3493 1 monslave secret slave
      SHUTDOWNCMD "touch /killpower/killpower" 
```
